#!/usr/bin/python3
import os
import sys
from sys import exit

if len(sys.argv) > 1:
	execute=""
	for i in range(len(sys.argv)):
		if i != 0:
			execute += sys.argv[i] + " "
	if sys.argv[1] == "-l":
		os.system("ls /opt/idur/bin/")
	elif sys.argv[1] == "-v":
		print("v0.2")
	else:
		os.system("/opt/idur/bin/" + execute)
else:
	print("""idur-exec
Use:
	idur-exec <idur-app-command>    execute idur app command
	idur-exec -l                    see execute commands
	idur-exec -v                    see version""")
